#namespace
NAMESPACE: staging

#kafka broker
KAFKA_IMAGE_NAME: confluentinc/cp-kafka
KAFKA_MEMORY: "1500Mi"
KAFKA_VOLUMENAME: fdk-dev-staging-kafka-1
KAFKA_STORAGESIZE: "199G"
KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"
