#namespace
NAMESPACE: prod

#kafka broker
KAFKA_IMAGE_NAME: confluentinc/cp-kafka
KAFKA_MEMORY: "100Mi"
KAFKA_VOLUMENAME: fdk-prod-kafka-3
KAFKA_STORAGESIZE: "99G"
KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "3"
