#namespace
NAMESPACE: staging

#kafka broker
KAFKA_IMAGE_NAME: confluentinc/cp-kafka
KAFKA_MEMORY: "100Mi"
KAFKA_VOLUMENAME: fdk-dev-staging-kafka-3
KAFKA_STORAGESIZE: "24G"
KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: "1"
