---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
    - ../../base/kafka

patchesStrategicMerge:
    - kafka-1-patch.yaml

transformers:
    - transformer-1.yaml
