apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: kafka
          imagePullPolicy: Always
          image: confluentinc/cp-kafka:7.8.0
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-1:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "-1"
            - name: KAFKA_LOG4J_ROOT_LOGLEVEL
              value: "WARN"
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: 1500Mi
              cpu: 100m
            limits:
              memory: 1500Mi
