---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
    - ../../base/schema-registry

patchesStrategicMerge:
    - schema-registry-1-patch.yaml

transformers:
    - transformer-1.yaml
