---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schema-registry
  labels:
    app: schema-registry-1
spec:
  replicas: 1
  serviceName: schema-registry-1
  selector:
    matchLabels:
        app: schema-registry-1
  template:
    metadata:
      labels:
        app: schema-registry-1
    spec:
      containers:
        - name: schema-registry
          env:
          - name: SCHEMA_REGISTRY_HOST_NAME
            value: "schema-registry-1"
          - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
            value: "PLAINTEXT://kafka-1:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  labels:
    app: schema-registry-1
spec:
  selector:
    app: schema-registry-1
