apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka-3
  name: kafka-3
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    app: kafka-3
status:
  loadBalancer: {}
