---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
    - ../../../base/schema-registry

patchesStrategicMerge:
    - ../schema-registry-2/schema-registry-2-patch.yaml

transformers:
    - transformer-2.yaml
