apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper-1
  name: zookeeper-1
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper-1
status:
  loadBalancer: {}
