apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper-1
  name: zookeeper-1
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  serviceName: zookeeper-1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - env:
          - name: ZOOKEEPER_SERVER_ID
            value: "1"
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"

          name: zookeeper-1
          image: {{ required "Missing value ZOOKEEPER_IMAGE_NAME" .Values.ZOOKEEPER_IMAGE_NAME }}
          imagePullPolicy: Always
          ports:
            - containerPort: 2181
          resources:
            requests:
              memory: {{ required "Missing value ZOOKEEPER_MEMORY" .Values.ZOOKEEPER_MEMORY | quote }}
          volumeMounts:
            - mountPath: /var/lib/zookeeper
              name: zookeeper-1-claim0
      restartPolicy: Always
      volumes:
        - name: zookeeper-1-claim0
          persistentVolumeClaim:
            claimName: zookeeper-1-claim0
status:
  replicas: 1
