kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper-1
  name: zookeeper-1-claim0
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  volumeName: {{ required "Missing value ZOOKEEPER_VOLUMENAME" .Values.ZOOKEEPER_VOLUMENAME }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "Missing value ZOOKEEPER_STORAGESIZE" .Values.ZOOKEEPER_STORAGESIZE | quote }}

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ required "Missing value ZOOKEEPER_VOLUMENAME" .Values.ZOOKEEPER_VOLUMENAME }}
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ required "Missing value ZOOKEEPER_STORAGESIZE" .Values.ZOOKEEPER_STORAGESIZE | quote }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ required "Missing value ZOOKEEPER_VOLUMENAME" .Values.ZOOKEEPER_VOLUMENAME }}
    fsType: ext4
