---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
    - ../../base/zookeeper
    - zookeeper-1-storage.yaml

patchesStrategicMerge:
    - zookeeper-1-patch.yaml

transformers:
    - transformer-1.yaml
