---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: zookeeper-1
  name: zookeeper-1-claim0
spec:
  storageClassName: ""
  volumeName: fdk-prod-zookeeper-1
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 9G
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: fdk-prod-zookeeper-1
spec:
  storageClassName: ""
  capacity:
    storage: 9G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: fdk-prod-zookeeper-1
    fsType: ext4
