apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: schema-registry-1
  name: schema-registry-1
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  serviceName: schema-registry-1
  selector:
    matchLabels:
      app: schema-registry-1
  template:
    metadata:
      labels:
        app: schema-registry-1
    spec:
      containers:
        - env:
          - name: SCHEMA_REGISTRY_HOST_NAME
            value: "schema-registry-1"
          - name: SCHEMA_REGISTRY_LISTENERS
            value: "http://0.0.0.0:8081"
          - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
            value: {{ required "Missing value SCHEMA_REGISTRY_BOOTSTRAP_SERVERS" .Values.SCHEMA_REGISTRY_BOOTSTRAP_SERVERS }}

          name: schema-registry-1
          image: {{ required "Missing value SCHEMA_REGISTRY_IMAGE_NAME" .Values.SCHEMA_REGISTRY_IMAGE_NAME }}
          imagePullPolicy: Always
          ports:
            - containerPort: 2181
          resources:
            requests:
              memory: {{ required "Missing value SCHEMA_REGISTRY_MEMORY" .Values.SCHEMA_REGISTRY_MEMORY | quote }}

      restartPolicy: Always
status:
  replicas: 1
