apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: schema-registry-2
  name: schema-registry-2
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: schema-registry-2
status:
  loadBalancer: {}
