---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  selector:
    matchLabels:
      app: zookeeper
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.9.0
          imagePullPolicy: Always
          env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
          ports:
            - containerPort: 2181
          resources:
            requests:
              memory: 100Mi
