---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka
  labels:
    app: kafka-3
spec:
  replicas: 1
  serviceName: kafka-3
  selector:
    matchLabels:
      app: kafka-3
  template:
    metadata:
      labels:
          app: kafka-3
    spec:
      containers:
        - name: kafka
          env:
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-3.prod:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              subPath: data
              name: kafka-3-claim0
      volumes:
        - name: kafka-3-claim0
          persistentVolumeClaim:
            claimName: kafka-3-claim0
---
kind: Service
apiVersion: v1
metadata:
  name: kafka
  labels:
    app: kafka-3
spec:
  selector:
    app: kafka-3
