---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
    - ../../../base/kafka
    - kafka-3-storage.yaml

patchesStrategicMerge:
    - kafka-3-patch.yaml

transformers:
    - transformer-3.yaml
