name: Deploy to staging

on:
  push:
    pull_request:
      types: [ ready_for_review, opened, reopened, synchronize ]
      branches:
        - main
  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        app: [ zookeeper-1, kafka-1, schema-registry-1 ]

    name: Deploy ${{ matrix.app }}
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud CLI for deploy
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}

      - name: Apply Helm template
        run: |
          helm template \
          ./helm-sources/${{ matrix.app }}/ > ./kubectlapply-${{ matrix.app }}.yaml \
          -f ./helm-sources/${{ matrix.app }}/values/staging.yaml 
          chmod o+w ./kubectlapply-${{ matrix.app }}.yaml
          cat kubectlapply-${{ matrix.app }}.yaml

      - name: Deploy to GCP
        run: |
          gcloud container clusters get-credentials digdir-fdk-dev --region europe-north1-a --project digdir-fdk-dev
          kubectl apply -f ./kubectlapply-${{ matrix.app }}.yaml --force
          kubectl --namespace=staging rollout restart statefulset ${{ matrix.app }}

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'Application: FDK Event Streaming Service - ${{ matrix.app }} | Environment: staging'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
